//
//  Constants.h
//  com.digitalCalc
//
//  Created by Belén  on 14/03/13.
//  Copyright (c) 2013 Mapplas. All rights reserved.
//

#ifndef com_digitalCalc_Constants_h
#define com_digitalCalc_Constants_h

#define LINE_SEGMENT 0
#define LINE_COLOR_RED 255.0/255.0
#define LINE_COLOR_GREEN 255.0/255.0
#define LINE_COLOR_BLUE 255.0/255.0
#define LINE_BRUSH_WIDE 5.0

#define DOT_SEGMENT 1
#define DOT_COLOR_RED 16.0/255.0
#define DOT_COLOR_GREEN 152.0/255.0
#define DOT_COLOR_BLUE 174.0/255.0
#define DOT_BRUSH_WIDE_IPAD 35.0
#define DOT_BRUSH_WIDE_IPHONE 25.0

#define ERASE_SEGMENT 2
#define ERASE_BRUSH_WIDE 35.0

#define COLOR_ALPHA_OPAQUE 1.0
#define COLOR_ALPHA_CLEAR 0.0

#define LEVEL_LOW 0
#define LEVEL_MEDIUM 1
#define LEVEL_HIGH 2

#define CALCULATOR_MODE_LEARN 0
#define CALCULATOR_MODE_GAME 1

#define GAME_MODE_COUNTDOWN 60
#define GAME_MODE_CORRECT_ANSWER_SECONDS 5
#define GAME_MODE_CORRECT_ANSWER_POINTS 10

#define RANKING_ELEMENTS 5

#define LOWER_LEVEL_MIN_ARGUMENT 1
#define LOWER_LEVEL_MAX_ARGUMENT 6
#define LOWER_LEVEL_SLIDER_MAX_NUMBER 20
#define LOWER_LEVEL_SLIDER_MIN_NUMBER 0

#define MEDIUM_LEVEL_MIN_ARGUMENT 1
#define MEDIUM_LEVEL_MAX_ARGUMENT 9
#define MEDIUM_LEVEL_SLIDER_MAX_NUMBER 30
#define MEDIUM_LEVEL_SLIDER_MIN_NUMBER 0

#endif
